import type { CmsEntry } from "./cms-content-pages";

export const initialFluteTabEntries: CmsEntry[] = [
  {
    id: "tab-beo-dat",
    collection: "flute-tabs",
    title: "Bèo dạt mây trôi",
    slug: "beo-dat-may-troi",
    excerpt: "Bèo dạt mây trôi – Dân ca quan họ Bắc Ninh",
    tag: "Tone C5 · Nhịp 4/4 · Dễ",
    price: "",
    content: "Bèo dạt mây trôi chốn xa xôi\ndo2 re2 mi2 sol2 la2 sol2 mi2 re2 do2\n\nAnh ơi em vẫn đợi cánh bèo dạt trôi\nla sol do2 re2 mi2 sol2 re2 do2 la sol",
    imageUrl: "",
    visible: true,
    sortOrder: 1,
    publishedAt: "2026-08-01",
  },
  {
    id: "tab-chieu-que-huong",
    collection: "flute-tabs",
    title: "Chiều trên quê hương",
    slug: "chieu-tren-que-huong",
    excerpt: "Chiều trên quê hương – Cảm âm dân gian",
    tag: "Tone C5 · Nhịp 2/4 · Trung bình",
    price: "",
    content: "Chiều nghiêng theo gió bờ tre ru êm đềm\nsol la sol mi re mi sol\n\nDòng sông lấp lánh chở câu ca về làng\nmi sol la do2 si la sol mi re mi sol do",
    imageUrl: "",
    visible: true,
    sortOrder: 2,
    publishedAt: "2026-08-02",
  },
  {
    id: "tab-vung-cao",
    collection: "flute-tabs",
    title: "Khúc sáo vùng cao",
    slug: "khuc-sao-vung-cao",
    excerpt: "Khúc sáo vùng cao – Bài luyện luyến láy",
    tag: "Tone G4 · Nhịp 6/8 · Trung bình",
    price: "",
    content: "Mây bay qua núi bước chân vui trên đồi\nsol la si re2 si la sol la sol mi\n\nTiếng sáo ngân dài gọi mùa xuân về đây\nsi re2 mi2 re2 si la sol mi sol la sol",
    imageUrl: "",
    visible: true,
    sortOrder: 3,
    publishedAt: "2026-08-03",
  },
  {
    id: "tab-ve-que",
    collection: "flute-tabs",
    title: "Về quê",
    slug: "ve-que",
    excerpt: "Về quê – Tác phẩm sáo trúc âm hưởng đồng quê",
    tag: "Tone C5 · Nhịp 4/4 · Nâng cao",
    price: "",
    content: "Theo em về quê nghe câu dân ca mẹ ru năm nào\nsol la do2 re2 mi2 mi2 re2 do2 la do2 sol la\n\nBờ tre xanh ngát con đò nhỏ xuôi dòng\ndo2 re2 mi2 sol2 la2 sol2 mi2 re2 do2",
    imageUrl: "",
    visible: true,
    sortOrder: 4,
    publishedAt: "2026-08-04",
  },
  {
    id: "tab-tinh-ca-tay-bac",
    collection: "flute-tabs",
    title: "Tình ca Tây Bắc",
    slug: "tinh-ca-tay-bac",
    excerpt: "Tình ca Tây Bắc – Bản chuyển soạn giai điệu vùng cao",
    tag: "Tone A4 · Nhịp 2/4 · Trung bình",
    price: "",
    content: "Rừng rừng hoa với chim ca vui tưng bừng\nsol sol la do2 re2 re2 do2 la sol\n\nSuối nước trong xanh soi bóng em gái bản\nmi2 sol2 mi2 re2 do2 re2 do2 la sol",
    imageUrl: "",
    visible: true,
    sortOrder: 5,
    publishedAt: "2026-08-05",
  },
];

export function getFluteTabBySlug(slug: string): CmsEntry | undefined {
  return initialFluteTabEntries.find((entry) => entry.slug === slug);
}

export const initialGuideEntries: CmsEntry[] = [
  {
    id: "guide-01",
    collection: "free-guides",
    title: "Cách lấy hơi và tạo tiếng sáo tròn, rõ",
    slug: "cach-lay-hoi-va-tao-tieng-sao-tron-ro",
    tag: "YouTube",
    price: "Sáo trúc căn bản",
    excerpt: "Hướng dẫn kỹ thuật lấy hơi bằng cơ hoành, khẩu hình chuẩn và cách tạo luồng hơi ổn định khi mới học.",
    content: "https://www.youtube.com/@saotrucauco",
    imageUrl: "/carousel-saotruc.webp",
    visible: true,
    sortOrder: 1,
    publishedAt: "2026-08-01",
  },
  {
    id: "guide-02",
    collection: "free-guides",
    title: "Mẹo sửa lỗi xì tiếng và rung ngón",
    slug: "meo-sua-loi-xi-tieng-va-rung-ngon",
    tag: "TikTok",
    price: "Mẹo luyện tập nhanh",
    excerpt: "Video ngắn chia sẻ mẹo khắc phục lỗi xì tiếng sáo, cách đặt môi êm và linh hoạt ngón tay.",
    content: "https://www.tiktok.com/@saotrucauco",
    imageUrl: "/carousel-dizi.webp",
    visible: true,
    sortOrder: 2,
    publishedAt: "2026-08-05",
  },
  {
    id: "guide-03",
    collection: "free-guides",
    title: "Chọn nhạc cụ và xây dựng lộ trình học sáo hiệu quả",
    slug: "chon-nhac-cu-va-xay-dung-lo-trinh-hoc",
    tag: "Bài viết",
    price: "Kiến thức chuyên sâu",
    excerpt: "So sánh chi tiết ưu nhược điểm của các loại sáo và hướng dẫn chọn cây sáo đầu tiên phù hợp với mục tiêu học tập.",
    content: "/huong-dan/chon-nhac-cu-va-xay-dung-lo-trinh-hoc",
    imageUrl: "/carousel-tieu.webp",
    visible: true,
    sortOrder: 3,
    publishedAt: "2026-08-10",
  },
];

export function getGuideBySlug(slug: string): CmsEntry | undefined {
  return initialGuideEntries.find((entry) => entry.slug === slug);
}
